spring:
  config:
    activate:
      on-profile: batch

  batch:
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none

  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/testdb1
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  quartz:
    properties:
      org:
        quartz:
          scheduler-name: QRTZ_
          threadPool:
            threadCount: 5

          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            misfireThreshold: 1000
            useProperties: true
            dataSource: qrtz

          dataSource:
            qrtz:
              driver: com.mysql.cj.jdbc.Driver
              jdbc-url: jdbc:mysql://db.clwna61sgtpo.ap-northeast-2.rds.amazonaws.com:3306/scheduler
              username: choizz
              password: 123qweasd

    job-store-type: jdbc

---
spring:
  config:
    activate:
      on-profile: local

  batch:
    job:
      enabled: false

  jpa:
    hibernate:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: true
    show-sql: true



  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  quartz:
    properties:
      org:
        quartz:
          scheduler-name: QRTZ_
          threadPool:
            threadCount: 5

          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            misfireThreshold: 1000
            useProperties: true

    job-store-type: memory

---

spring:
  profiles:
    active: circuit-breaker-batch

resilience4j:
  circuitbreaker:
    instances:
      internalPaymentApiClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - com.team33.moduleexternalapi.exception.PaymentApiException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException
          - org.springframework.web.client.HttpServerErrorException

  retry:
    instances:
      internalPaymentApiClient:
        maxAttempts: 3
        waitDuration: 1000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException
        ignoreExceptions:
          - com.team33.moduleexternalapi.exception.PaymentApiException

    