server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "app_info_logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "app_info_logs"
          level: "info"
          __path__: "/Users/choi/pillivery/server/module-logging/logs/info.log"

  - job_name: "app_warn_logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "app_warn_logs"
          level: "warn"
          __path__: "/Users/choi/pillivery/server/module-logging/logs/warn.log"

  - job_name: "app_error_logs"
#    pipeline_stages:
#      - regex:
#          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) (?P<message>.*)'
#      - timestamp:
#          format: "2006-01-02 15:04:05.000"
#          source: time
#          location: "Asia/Seoul"
    static_configs:
      - targets:
          - localhost  # Changed from host.docker.internal
        labels:
          job: "app_error_logs"
          level: "error"
          __path__: "/Users/choi/pillivery/server/module-logging/logs/error.log"


  - job_name: "app_json_logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "app"
          __path__: "/Users/choi/pillivery/server/module-logging/logs/json.log"


