
spring:
  config:
    activate:
      on-profile: batch

  batch:
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.6:3306/batch?serverTimezone=Asia/Seoul&jdbcCompliantTruncation=false&rewriteBatchedStatements=true

  quartz:
    properties:
      org:
        quartz:
          scheduler-name: QRTZ_
          threadPool:
            threadCount: 5

          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            misfireThreshold: 1000
            useProperties: true
            dataSource: qrtz

          dataSource:
            qrtz:
              driver: com.mysql.cj.jdbc.Driver
              jdbc-url: jdbc:mysql://192.168.0.6:3306/scheduler
              username: choizz
              password: 123qweasd

    job-store-type: jdbc

resilience4j:
  circuitbreaker:
    instances:
      internalPaymentApiClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - com.team33.modulebatch.exception.BatchApiException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException

  retry:
    instances:
      internalPaymentRetry:
        maxAttempts: 3
        waitDuration: 300ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        ignoreExceptions:
          - com.team33.modulebatch.exception.BatchApiException

