spring:
  config:
    activate:
      on-profile: local

resilience4j:
  circuitbreaker:
    instances:
      paymentApiClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 90
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException

  thread-pool-bulkhead:
    instances:
      paymentApiClient:
        coreThreadPoolSize: 20
        maxThreadPoolSize: 50
        queueCapacity: 50
        keepAliveDuration: 15s

  timelimiter:
    instances:
      paymentLookUpClient:
        timeoutDuration: 5s
        cancelRunningFuture: true

  retry:
    instances:
      paymentApiClient:
        maxAttempts: 3
        waitDuration: 2000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.ConnectException
          - org.springframework.web.reactive.function.client.WebClientRequestException
        ignoreExceptions:
          - com.team33.moduleexternalapi.exception.PaymentApiException

      paymentLookUpClient:
        maxAttempts: 5
        waitDuration: 1000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException
        ignoreExceptions:
          - com.team33.moduleexternalapi.exception.PaymentApiException