CREATE TABLE subscription_order
(
    subscription_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP with time zone,
    updated_at            TIMESTAMP with time zone,
    main_item_name        VARCHAR(255),
    total_quantity        INT                                     NOT NULL,
    period                INT                                     NOT NULL,
    subscription          BOOLEAN                                 NOT NULL,
    next_payment_day      TIMESTAMP with time zone,
    last_payment_day      TIMESTAMP with time zone,
    sid                   VARCHAR(255),
    tid                   VARCHAR(255),
    total_price           INT                                     NOT NULL,
    total_discount_price  INT                                     NOT NULL,
    real_name             VARCHAR(255),
    phone                 VARCHAR(255),
    city                  VARCHAR(255),
    detail_address        VARCHAR(255),
    order_status          VARCHAR(255),
    user_id               BIGINT,
    CONSTRAINT pk_subscriptionorder PRIMARY KEY (subscription_order_id)
);