version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cache:/tmp/nginx
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128m'

